"""remove unique from exhibits.museum_id

Revision ID: 138797f366f3
Revises: 94709bd69014
Create Date: 2026-01-08 19:34:29.715016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138797f366f3'
down_revision: Union[str, Sequence[str], None] = '94709bd69014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('exhibits_museum_id_key'), 'exhibits', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('exhibits_museum_id_key'), 'exhibits', ['museum_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
